### ISSUE TITLE
Merge terminate_pods and delete_pods to avoid confusion and unnecessary code bloat

### ISSUE THREAD

**Issue by ecourreges-orange** [chaostoolkit/chaostoolkit-kubernetes#122]
**Is your feature request related to a problem? Please describe.**
It is weird to see in the documentation that delete_pods and terminate_pods have completely different argument signature for a pretty similar functionality.
It is even weirder to see in the python sources that terminate_pods and delete_pods both end up calling delete_pod, and delete_pods is more or less the same as calling terminate_pods with a grace_period of 0.  
Was there an intent I am not grasping here?

**Describe the solution you'd like**
I think terminate_pods should be deprecated, and delete_pods (which corresponds to the real k8s term) should adopt the signature of terminate_pods (with random/grace_period, etc.), and in the code, one calls the other so they become really equal.

**Describe alternatives you've considered**
Right now, I recommended my dev to use terminate_pods with a grace period of 0, as it doesn't force to know the pod name thanks to the rand functionality. Labels alone in delete_pods don't easily allow deleting one pod out of a replica set.

Let me know what you think and if you require a PR for this.
Regards.

**Comment by Lawouach** [comment]
Hello Emmanuel.

Sorry for the looooong delay. I think unfortunately the extension has grown in a non very consolidated way. You're right that both actions aren't necessary. I'll see to at least deprecate `delete_pods` in favour of the other one.
