### ISSUE TITLE
exec_in_pods cannot use space in the command itself

### ISSUE THREAD

**Issue by kpk-pl** [chaostoolkit/chaostoolkit-kubernetes#127]
**Describe the bug**
The code does a split() on the string provided as a cmd. https://github.com/chaostoolkit/chaostoolkit-kubernetes/blob/master/chaosk8s/pod/actions.py#L126 

This makes it impossible to use some commands (with provided extracts from logs):
- "python -c 'import urllib2'" --> command execution ['python', '-c', "'import", "urllib2'"]

while some others just have strange results:
- "echo 'Long sentence'" ->  command execution ['echo', "'Long", "sentence'"] --> 'stdout': "'Long sentence'\n" (additional quotes)

**Expected behavior**
The provided command is passed to the selected PODs without any manipulations. Those commands from above work in kubectl. If this is not possible with the kubernetes API right now, accept an array in the 'cmd' field that would be passed to kubernetes without modifications

**Additional context**

**Comment by kpk-pl** [comment]
Here is my proposal to fix this by extending the interface to allow passing an array of command parameters (just like to Subproces) while keeping backward compatibility: https://github.com/kpk-pl/chaostoolkit-kubernetes/commit/011a1f932098440166a687e6f636f7694cd66143
If you're happy with this approach I will add UT and submit a PR

**Comment by ciaranevans** [comment]
@kpk-pl this looks reasonable to me, feel free to raise the PR 😄

**Comment by kpk-pl** [comment]
@ciaranevans @Lawouach if you could kindly take a look at https://github.com/chaostoolkit/chaostoolkit-kubernetes/pull/129 , maybe review and approve workflow.
