### ISSUE TITLE
Link to the documentation in the README is broken

### ISSUE THREAD

**Issue by markrouz** [chaostoolkit/chaostoolkit-kubernetes#152]
**Describe the bug**
Link to the documentation in the README is broken

**Expected behavior**
Link to the documentation points to https://chaostoolkit.org/drivers/kubernetes/#exported-activities

**Additional context**

**Comment by cdsre** [comment]
I believe this is the correct link these days.

**Comment by Lawouach** [comment]
Indeed the link is correct now. Thanks @markrouz for the initial issue.
