### ISSUE TITLE
chaostoolkit-kubernetes: Stress memory calls a stress cpu

### ISSUE THREAD

**Issue by ALupin813** [chaostoolkit/chaostoolkit-kubernetes#161]
Hi, 

Not sure about my conclusion but I think there is an issue with stress_memory function. It's currently calling a chaosMesh CPU stressor.

https://github.com/chaostoolkit/chaostoolkit-kubernetes/blob/b1019b2a810683dda6fafc4d9cae2de433314966/chaosk8s/chaosmesh/stress/actions.py#L128

Correction proposal:
 
    Stress the memory to impact a process/container.
    See: https://chaos-mesh.org/docs/simulate-heavy-stress-on-kubernetes/
    """

    r = yaml.safe_load(
        dedent(
            """---
    apiVersion: chaos-mesh.org/v1alpha1
    kind: StressChaos
    metadata: {}
    spec:
      selector: {}
      stressors:
        memory: {}
    """
        )
    )

    r["metadata"]["name"] = name
    r["metadata"]["ns"] = ns

    s = r["spec"]
    m = s["stressors"]["memory"]
    m["workers"] = workers
    m["size"] = size
    m["time"] = time_to_get_to_size
    m["oomScoreAdj"] = oom_score    """

**Comment by ALupin813** [comment]
PR created. 
Done on web IDE so I was not able to run 'make test', 'make format' and 'make lint'.
Not familiar with Github so let me know if I have things to correct

**Comment by Lawouach** [comment]
Thank you for the change. It's now merged in :)
