### ISSUE TITLE
kill_microservice not working due to naked 'body' args for functions

### ISSUE THREAD

**Issue by maroda** [chaostoolkit/chaostoolkit-kubernetes#42]
This looks similar to https://github.com/chaostoolkit/chaostoolkit-kubernetes/issues/34

It appears `actions.py` has several incorrect instances of `body` as an argument.

If I edit to read `body=body` as in here for `kill_microservice`: https://github.com/chaostoolkit/chaostoolkit-kubernetes/blob/master/chaosk8s/actions.py#L67

The deployment will correctly be deleted. Without that edit, I will get the following:
```
[2019-06-19 17:32:43 ERROR]   => failed: TypeError: delete_namespaced_deployment() takes 3 positional arguments but 4 were given
```

And the function will not run, no deployment is deleted.

This also appears two other places:

https://github.com/chaostoolkit/chaostoolkit-kubernetes/blob/master/chaosk8s/actions.py#L81

https://github.com/chaostoolkit/chaostoolkit-kubernetes/blob/master/chaosk8s/actions.py#L95

**Comment by Lawouach** [comment]
Hi @maroda,

This is indeed likely a bug here. Looking at the API https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/ExtensionsV1beta1Api.md#delete_namespaced_deployment, the third positional argument is not `body` indeed. 

I'll fix it.

Cheers
