### ISSUE TITLE
Question: when doing chao init, it stuck at defining an experimental method

### ISSUE THREAD

**Issue by lcwus2** [chaostoolkit/chaostoolkit-kubernetes#54]
I use chaostoolkit-kubernetes
when doing chao init, it stuck at defining an experimental method like this:
![image](https://user-images.githubusercontent.com/30100640/66534355-8ac74a80-eb48-11e9-9e14-030dbd46f0ab.png)
what should I press to choose this? I see docs about chaos init, but that  is not the same as above.

**Comment by Lawouach** [comment]
Hello,

I think discover and init need a solid clean up indeed. Let me try to see if I run into the same problem.

Thanks

**Comment by Lawouach** [comment]
Okay, indeed, I have the same behavior.

When the list is shown, remember the number you are interested in and press 'q'. This will leave the menu selection and back to the main menu.

let me if that helps.

**Comment by lcwus2** [comment]
> Okay, indeed, I have the same behavior.
> 
> When the list is shown, remember the number you are interested in and press 'q'. This will leave the menu selection and back to the main menu.
> 
> let me if that helps.

it works！thanks
I have another one question：written “press return to use or not set any value” above, but  I press return, it let me input again！
![image](https://user-images.githubusercontent.com/30100640/66693132-17ecd980-ecd8-11e9-87ff-68ba360b3148.png)

**Comment by lcwus2** [comment]
by the way,  tutorials and videos in https://docs.chaostoolkit.org seems too old, making beginner a little confused. 
Hope to see new tutorials later

**Comment by Lawouach** [comment]
Hey @lcwus2, let's move this to https://github.com/chaostoolkit/chaostoolkit/issues/131 (that you opened) as it's a CLI/docs question, not one about this extension.
