### ISSUE TITLE
What do you mean by "name" parameter in function microservice_available_and_healthy?

### ISSUE THREAD

**Issue by SidGrundfos** [chaostoolkit/chaostoolkit-kubernetes#55]
In the documentation it states look for deployment by "name" but when I give the deployment name it always fails stating microservice not found.

**Comment by SidGrundfos** [comment]
But the "name" is mandatory parameter, even if I give the name in "Label_selector" it fails with the same message

**Comment by Lawouach** [comment]
Mmh, it's been a while since I have used that action so my recollection might be a bit blurry. I'll have to try again.

**Comment by SidGrundfos** [comment]
![image](https://user-images.githubusercontent.com/53938860/67756738-d760c000-fa3a-11e9-80f3-a0bd3ccb10aa.png)

**Comment by SidGrundfos** [comment]
![image](https://user-images.githubusercontent.com/53938860/67756778-e9426300-fa3a-11e9-9a52-5b189ec400c4.png)

**Comment by Lawouach** [comment]
The label selector syntax follows what you'd use in the kubectl command.

So, I would assume:

```
"arguments": {
    "name": "grundfosgicwmncapi"
}
```

should work and look for resources that have a label called `name`. This has changed from https://github.com/chaostoolkit/chaostoolkit-kubernetes/pull/53/commits/16960b987c502c9bcd104922c5e0ba37927a2aa4 (not yet released) where it won't look for a label called `name`  but will look at the metadata itself.

So, if your deployment doesn't expose a specific `name: grundfosgicwmncapi` label, then with the current release of the extension, it won't find anything indeed.

Once I have released the change, you will not need a specific `name`  label.

**Comment by SidGrundfos** [comment]
![image](https://user-images.githubusercontent.com/53938860/67757932-0415d700-fa3d-11e9-954e-5cc2c14dbc99.png)

**Comment by SidGrundfos** [comment]
How can I make it work with this?

**Comment by Lawouach** [comment]
Add a new label alongside `app: ...`

`name: grundfosgicwmncapi`

**Comment by SidGrundfos** [comment]
Thanks! It seems to be working
