### ISSUE TITLE
update api version for chaosk8s extension 

### ISSUE THREAD

**Issue by r1sharma** [chaostoolkit/chaostoolkit-kubernetes#63]
Latest chaosk8s version is currently looking for apis in kube cluster with version `apps/v1beta1` as per code [here](https://github.com/chaostoolkit/chaostoolkit-kubernetes/blob/0.21.0/chaosk8s/actions.py#L55).
Latest version of kubectl accepts only `apps/v1` version for the [apis](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/).
We should upgrade it to the latest version to be compatible with latest kubectl version.

**Comment by Lawouach** [comment]
This been fixed in 0.24.0. Cheers
