### ISSUE TITLE
gitignore .idea folder

### ISSUE THREAD

**Issue by tdevilleduc** [chaostoolkit/chaostoolkit-kubernetes#71]
Is it possible to ignore .idea folder ?
I use Intellij and i need to ignore thoses files every times i create a branch on chaostoolkit-kubernetes project

Do i need to create a pull request for that ?

**Comment by Lawouach** [comment]
Happy to ignore it indeed. Feel free to create a small PR indeed :)

**Comment by tdevilleduc** [comment]
Thank you !
https://github.com/chaostoolkit/chaostoolkit-kubernetes/pull/72
