### ISSUE TITLE
What is the tolerance for read_pod_logs

### ISSUE THREAD

**Issue by SidGrundfos** [chaostoolkit/chaostoolkit-kubernetes#81]
the following probe fails with error: 

Steady state probe 'fetch-ziptranslatorservice-zipservice-pod-logs' is not in the given tolerance so failing this experiment

{
            "name": "fetch-ziptranslatorservice-zipservice-pod-logs",
            "type": "probe",
            "tolerance": true,
            "provider": {
              "func": "read_pod_logs",
              "arguments": {
                  "label_selector": "name=zipservice",
                  "last": "30m",
                  "ns": "core"
              },
              "type": "python",
              "module": "chaosk8s.pod.probes"
            }
          }

**Comment by Lawouach** [comment]
Hello!

I think the read_pod_logs probe doesn't return a boolean so the tolerance would be incorrect. Maybe use a jsonpath or regex instead?

for instance:
https://docs.chaostoolkit.org/reference/tutorials/tolerance/#validate-the-stdoutstderr-of-a-process

**Comment by SidGrundfos** [comment]
Thanks for the help!
I have added something like this
{
          "name": "fetch-guamapper-pod-logs",
          "type": "probe",
          "tolerance": {
            "type": "regex",
            "pattern": "@timestamp",
            "target": "stdout"
          },
          "provider": {
            "func": "read_pod_logs",
            "arguments": {
                "name": "guamapper",
                "last": "30m",
                "ns": "core"
            },
            "type": "python",
            "module": "chaosk8s.pod.probes"
          }
        }

where the logs I should receive from kubectl is similar to - 
{"@timestamp":"2020-02-25T07:27:30.7609245Z","Message":"Deleted Source blob \"51558226fb58524ca6b3137c150e308f/02060001053ACC5A_10_0#2020-02-25T07-29-55Z.json.gz\" From Container.","BlobName":"51558226fb58524ca6b3137c150e308f/02060001053ACC5A_10_0#2020-02-25T07-29-55Z.json.gz","SourceContext":"Grundfos.GiC.ZipTranslatorService.Services.BlobFileOperations.BlobOperationManager"}

{"@timestamp":"2020-02-25T07:27:30.8889674Z","Message":"Marked file upload notification as complete:DeviceId:\"51558226fb58524ca6b3137c150e308f\",BlobName: \"51558226fb58524ca6b3137c150e308f/02060001053ACC5A_10_0#2020-02-25T07-29-55Z.json.gz\", BlobUrl:\"https://gfstoiotfileuploadpazwe.blob.core.windows.net/wwnfiles/51558226fb58524ca6b3137c150e308f/02060001053ACC5A_10_0%232020-02-25T07-29-55Z.json.gz\", BlobSizeInBytes:7156, LastUpdatedTime:02/25/2020 07:27:26 +00:00, EnqueuedTimeUtc:02/25/2020 07:27:28","Level":"Verbose","DeviceId":"51558226fb58524ca6b3137c150e308f","BlobName":"51558226fb58524ca6b3137c150e308f/02060001053ACC5A_10_0#2020-02-25T07-29-55Z.json.gz","BlobUri":"https://gfstoiotfileuploadpazwe.blob.core.windows.net/wwnfiles/51558226fb58524ca6b3137c150e308f/02060001053ACC5A_10_0%232020-02-25T07-29-55Z.json.gz","BlobSizeInBytes":7156,"LastUpdatedTime":"2020-02-25T07:27:26.0000000+00:00","EnqueuedTimeUtc":"2020-02-25T07:27:28.1185446Z","SourceContext":"Grundfos.GiC.ZipTranslatorService.ZipTranslator"}

where I am searching for "timestamp"

the Pod Yaml contains labels -
labels:
    app.kubernetes.io/environment: p
    app.kubernetes.io/instance: guamapper
    app.kubernetes.io/name: guamapper
    pod-template-hash: 574f89f4cd


Am I missing something? Or is there a syntax error, I am looking for last 30 minutes logs

**Comment by nitinbhat** [comment]
Is there any workaround for this? I am facing same issue

**Comment by Lawouach** [comment]
Hey folks. I'm finally looking into this issue now. I'll report soon.

**Comment by Lawouach** [comment]
The builtin regex tolerance wasn't well adapted here so I've created a dedicated probe for this task:


```json
{
    "title": "Check pod logs",
    "description": "n/a",
    "runtime": {
        "hypothesis": {
            "strategy": "after-method-only"
        }
    },
    "steady-state-hypothesis": {
        "title": "extract-logs-with-regex",
        "probes": [
            {
                "name": "read-pod-logs",
                "type": "probe",
                "tolerance": {
                    "name": "search-probe",
                    "type": "probe",
                    "provider": {
                        "type": "python",
                        "module": "chaosk8s.pod.probes",
                        "func": "should_be_found_in_logs",
                        "arguments": {
                            "pattern": "startup",
                            "all_containers": false
                        }
                    }
                },
                "provider": {
                    "type": "python",
                    "module": "chaosk8s.pod.probes",
                    "func": "read_pod_logs",
                    "arguments": {
                        "last": "60s",
                        "label_selector": "app=producer",
                        "container_name": "producer"
                    }
                }
            }
        ]
    },
    "method": [
        {
            "type": "action",
            "name": "terminate-producer-pod",
            "provider": {
                "type": "python",
                "module": "chaosk8s.pod.actions",
                "func": "terminate_pods",
                "arguments": {
                    "label_selector": "app=producer"
                }
            },
            "pauses": {
                "after": 10
            }
        }
    ]
}
```

The [should_be_found_in_logs](https://chaostoolkit.org/drivers/kubernetes/#should_be_found_in_logs) probe takes the output of `read_pod_logs` and search for a pattern in container's logs.

I hope this will do.
